"""What `make codegen`, `make codegen-check` and `make codegen-verify` share: where the method and its tree are, and the policies.

The three gestures work on one method, the one in the package's `method/` directory, read the way a
run reads it (`lib/method_source.py`): a bundle of `.mthds` files sent inline, or a `method.json`
naming a catalog id (`method_id`) or a published address (`method_ref`) for the API to resolve. They
write and read the package's `generated/` directory, whose files are named in `lib/contracts.py` so
that the CLI and these scripts cannot disagree about them:

- the codegen tree, written verbatim from `POST /v1/codegen` by the SDK's `write_codegen_tree`:
  the typed models and `codegen.lock`, which signs them;
- `contracts.json`, the three payloads of one `POST /v1/pipe-io` call, rendered by
  `render_contracts` so that the same answer always gives the same bytes;
- `__init__.py`, which makes the tree a package `binding.py` imports its models from;
- `sources.json`, the sidecar recording the hash of each source the tree was generated from, and of
  each file the script writes itself and the lock does not sign (`DERIVED_ARTIFACTS`).

The policies every gesture holds, each with its test, are `webapp-js`'s (`docs/codegen.md`):

- **Symlinks and special files are refused** under `method/` and `generated/`, so nothing outside
  the package is read as the method or written through a link.
- **UTF-8 is fatal**: a file that does not decode is refused, never read with replacement characters.
- **A path the server names must stay inside the tree**, and must not land on a file the script
  writes itself (`is_contained_path`, `WRITER_OWNED`).
- **The key never travels in plaintext** to a host that is not local (`insecure_base_url_reason`).

The ported module is `webapp-js`'s `scripts/lib/shared.mts`.
"""

import hashlib
import json
import os
import stat
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, cast
from urllib.parse import urlparse

from mthds.protocol.input_form import InputForm
from mthds.protocol.output_form import OutputForm
from mthds.protocol.pipe_io_contracts import PipeIOContracts
from pipelex_sdk.crate_models import CodegenRequest, CodegenTarget, CrateInvalidReport, MthdsFileItem, PipeIORequest, PipeIOValidReport

from pipelex_method_cli_python.lib.contracts import (
    CONTRACTS_FILENAME,
    GENERATED_DIRNAME,
    INIT_FILENAME,
    LOCK_FILENAME,
    SOURCES_SIDECAR,
    ContractsDocument,
)
from pipelex_method_cli_python.lib.manifest import MANIFEST_FILENAME, MethodSelector, parse_manifest
from pipelex_method_cli_python.lib.method_source import BUNDLE_SUFFIX, METHOD_DIRNAME, PACKAGE

#: The template's root, the directory the Makefile runs the scripts from.
CLI_ROOT = Path(__file__).resolve().parent.parent

#: The projection the typed models are generated in.
TARGET: CodegenTarget = "python-pydantic"

#: The files the script writes itself, which the codegen lock does not sign: their hashes ride in the sidecar.
DERIVED_ARTIFACTS: tuple[str, ...] = (CONTRACTS_FILENAME, INIT_FILENAME)

#: Every file the script writes rather than the server: a server artifact landing on one is refused.
WRITER_OWNED = frozenset({LOCK_FILENAME, SOURCES_SIDECAR, *DERIVED_ARTIFACTS})

#: The directory Python writes its bytecode cache to, which no walk reads as part of a tree.
BYTECODE_CACHE = "__pycache__"

#: What every refusal of the check says to do.
REGENERATE = "Run `make codegen` to regenerate."

#: The hosts the key may be sent to over plaintext `http:`, being this machine.
LOCAL_HOSTS = frozenset({"localhost", "127.0.0.1", "::1"})

#: What `sources.json` says about itself.
SIDECAR_COMMENT = (
    "Generated by `make codegen`. `sources` is the SHA-256 of everything the method is generated from: every "
    ".mthds file of its bundle, or the method.json naming where it lives, so the offline check can say to "
    "regenerate after an edit; `derived` is the SHA-256 of each file the codegen writes itself and the codegen "
    "lock does not sign. Not part of the codegen lock; do not edit."
)

#: What `contracts.json` says about itself.
CONTRACTS_COMMENT = (
    "Generated by `make codegen`; do not edit. The method's pipe IO contracts and its input and output form "
    "descriptors, exactly as POST /v1/pipe-io returned them, keyed by namespaced pipe reference. The CLI derives "
    "its options from `input_form` and builds each input's payload against `pipe_io_contracts`. Not signed by the "
    "codegen lock: its SHA-256 is in sources.json under `derived`, and `make codegen-check` compares it."
)

#: What the generated package's `__init__.py` holds.
INIT_CONTENT = '"""The method\'s typed models and contracts, written by `make codegen`: do not edit."""\n'


class CodegenSetupError(Exception):
    """A tree or a method the gestures refuse to read, whatever the network says: there is no verdict."""


class SymlinkRefusedError(CodegenSetupError):
    """A symbolic link or a special file under `method/` or `generated/`."""

    def __init__(self, where: str, kind: str) -> None:
        allowed = f"only regular files and directories are allowed under {METHOD_DIRNAME}/ and {GENERATED_DIRNAME}/"
        super().__init__(f"refusing {kind} at {where}: {allowed}.")


class NonUtf8FileError(CodegenSetupError):
    """A file that is not UTF-8, which neither the API nor the codegen would read."""

    def __init__(self, where: str) -> None:
        super().__init__(f"{where} is not valid UTF-8.")


class MethodLayoutError(CodegenSetupError):
    """A `method/` directory that names its method in two ways at once."""


@dataclass(frozen=True)
class Layout:
    """Where the gestures read the method and write its tree: the import package's directory, `src/<package>/`.

    The tests point it at a directory of their own, so that no test writes into the package's tree.
    """

    package_dir: Path

    @property
    def method_dir(self) -> Path:
        """The package's `method/` directory."""
        return self.package_dir / METHOD_DIRNAME

    @property
    def generated_dir(self) -> Path:
        """The package's `generated/` directory."""
        return self.package_dir / GENERATED_DIRNAME

    def describe(self, path: Path) -> str:
        """A path as a message names it: relative to the template's root, or to the package's parent."""
        for base in (CLI_ROOT, self.package_dir.parent):
            try:
                return path.relative_to(base).as_posix()
            except ValueError:
                continue
        return str(path)


#: The package's own layout, which the gestures work on when they run for real.
PACKAGE_LAYOUT = Layout(CLI_ROOT / "src" / PACKAGE)


def refuse_symlink_root(directory: Path, layout: Layout) -> None:
    """Refuse a root that is itself a symbolic link; a missing one is left for the caller to report.

    Raises:
        SymlinkRefusedError: The directory is a symbolic link.
    """
    if directory.is_symlink():
        raise SymlinkRefusedError(layout.describe(directory), "a symlink")


def walk(directory: Path, layout: Layout) -> list[str]:
    """Every regular file under `directory`, as sorted POSIX paths relative to it, Python's bytecode cache aside.

    Raises:
        SymlinkRefusedError: The directory or anything under it is a symbolic link or a special file.
        FileNotFoundError: The directory does not exist.
    """
    refuse_symlink_root(directory, layout)
    found: list[str] = []
    _walk_into(directory, "", found, layout)
    return sorted(found)


def _walk_into(directory: Path, prefix: str, found: list[str], layout: Layout) -> None:
    with os.scandir(directory) as entries:
        for entry in entries:
            relative = f"{prefix}{entry.name}"
            mode = entry.stat(follow_symlinks=False).st_mode
            if stat.S_ISDIR(mode):
                if entry.name != BYTECODE_CACHE:
                    _walk_into(Path(entry.path), f"{relative}/", found, layout)
            elif stat.S_ISREG(mode):
                found.append(relative)
            else:
                kind = "a symlink" if stat.S_ISLNK(mode) else "a special file"
                raise SymlinkRefusedError(layout.describe(Path(entry.path)), kind)


def read_text_file(path: Path, layout: Layout) -> str:
    """A file's text, decoded as UTF-8 with no replacement.

    Raises:
        NonUtf8FileError: The bytes are not UTF-8.
    """
    data = path.read_bytes()
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise NonUtf8FileError(layout.describe(path)) from exc


def hash_source(content: str) -> str:
    """The SHA-256 of a text, its line endings folded to LF first so that a checkout's line endings change nothing."""
    normalized = content.replace("\r\n", "\n").replace("\r", "\n")
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class CodegenSource:
    """The one method of the package, as the crate routes name it, with the hashes of what it is read from."""

    #: The bundle's files, each labelled `method/<path>`, when the method is a bundle.
    files: tuple[MthdsFileItem, ...] | None = None
    #: The catalog id or address `method.json` names, when the method lives elsewhere.
    selector: MethodSelector | None = None
    #: The SHA-256 of each source, keyed by its package-relative label, `method/<path>`.
    source_hashes: dict[str, str] = field(default_factory=dict[str, str])

    def describe(self) -> str:
        """The method as a report line names it."""
        if self.selector is not None and self.selector.method_ref is not None:
            return f"method_ref {self.selector.method_ref}"
        if self.selector is not None and self.selector.method_id is not None:
            return f"method_id {self.selector.method_id}"
        return f"the bundle in {METHOD_DIRNAME}/"

    def _selector_kwargs(self) -> dict[str, object]:
        if self.selector is None:
            return {"files": list(self.files or ())}
        return {"method_id": self.selector.method_id, "method_ref": self.selector.method_ref}

    def codegen_request(self) -> CodegenRequest:
        """The `/v1/codegen` request: the method and the projection, with no `pipe_ref`, which the `types` kind refuses."""
        return CodegenRequest.model_validate({**self._selector_kwargs(), "kind": "types", "target": TARGET})

    def pipe_io_request(self) -> PipeIORequest:
        """The `/v1/pipe-io` request for every pipe the method loads; a named method also asks for its files back."""
        if self.selector is None:
            return PipeIORequest.model_validate({**self._selector_kwargs(), "all_pipes": True})
        return PipeIORequest.model_validate({**self._selector_kwargs(), "all_pipes": True, "include_files": True})


def discover_source(layout: Layout) -> CodegenSource | None:
    """The method in the package's `method/`, or `None` when there is none, which is the template as shipped.

    Raises:
        SymlinkRefusedError: Something under `method/` is a link or a special file.
        NonUtf8FileError: A source file is not UTF-8.
        MethodLayoutError: `method/` holds both `.mthds` files and a `method.json`.
        ManifestError: The `method.json` does not name exactly one method.
    """
    method_dir = layout.method_dir
    refuse_symlink_root(method_dir, layout)
    if not method_dir.is_dir():
        return None
    paths = walk(method_dir, layout)
    bundles = [path for path in paths if path.endswith(BUNDLE_SUFFIX)]
    if MANIFEST_FILENAME in paths and bundles:
        msg = (
            f"{layout.describe(method_dir)}/ holds both {MANIFEST_FILENAME} and .mthds files ({', '.join(bundles)}): "
            "a method is generated from its own bundle or from the method the manifest names, never both."
        )
        raise MethodLayoutError(msg)
    if MANIFEST_FILENAME in paths:
        label = f"{METHOD_DIRNAME}/{MANIFEST_FILENAME}"
        content = read_text_file(method_dir / MANIFEST_FILENAME, layout)
        return CodegenSource(selector=parse_manifest(content, origin=label), source_hashes={label: hash_source(content)})
    if not bundles:
        return None
    files: list[MthdsFileItem] = []
    hashes: dict[str, str] = {}
    for relative in bundles:
        content = read_text_file(method_dir / relative, layout)
        label = f"{METHOD_DIRNAME}/{relative}"
        files.append(MthdsFileItem(content=content, source=label))
        hashes[label] = hash_source(content)
    return CodegenSource(files=tuple(files), source_hashes=hashes)


def invalid_lines(report: CrateInvalidReport, *, lead: str = "the method does not resolve") -> list[str]:
    """A crate route's refusal of the method, as the lines a report prints: the message, then each item."""
    return [f"{lead}: {report.message}", *(f"    {item.source or '?'}: {item.message}" for item in report.validation_errors)]


def not_runnable_reason(report: PipeIOValidReport) -> str | None:
    """Why a method the route reports `is_runnable: false` is refused, naming its pending signatures."""
    if report.is_runnable:
        return None
    pending = ", ".join(report.pending_signatures) or "(the API named none)"
    return (
        f"the method is not runnable: these pipes are still declared as signatures, with no implementation: {pending}. "
        "Implement them in the bundle, then regenerate."
    )


def render_contracts(pipe_io_contracts: PipeIOContracts, input_form: InputForm, output_form: OutputForm) -> str:
    """`contracts.json`'s bytes for one `/v1/pipe-io` answer: the same answer always renders the same text.

    The payloads go through the `mthds.protocol` models `lib/contracts.py` reads them back with, so a
    file the CLI could not read is never written, and their members come out in the models' order.
    """
    document = ContractsDocument(comment=CONTRACTS_COMMENT, pipe_io_contracts=pipe_io_contracts, input_form=input_form, output_form=output_form)
    return json.dumps(document.model_dump(mode="json"), indent=2, ensure_ascii=False) + "\n"


def derived_artifacts(report: PipeIOValidReport) -> dict[str, str]:
    """The files the script writes beside the codegen tree, by name, with their content."""
    return {
        CONTRACTS_FILENAME: render_contracts(report.pipe_io_contracts, report.input_form, report.output_form),
        INIT_FILENAME: INIT_CONTENT,
    }


def render_sidecar(source_hashes: dict[str, str], derived: dict[str, str]) -> str:
    """`sources.json`'s bytes: the comment, the sources' hashes and the derived files' hashes, keys sorted."""
    document = {
        "comment": SIDECAR_COMMENT,
        "sources": dict(sorted(source_hashes.items())),
        "derived": {name: hash_source(content) for name, content in sorted(derived.items())},
    }
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def compare_sidecar(generated_dir: Path, current_sources: dict[str, str], layout: Layout) -> list[str]:
    """What the sidecar says is stale about a tree: a source edited, added or removed, or a derived file changed.

    Each problem is one line, `stale-source: …` or `derived: …`, sorted; none means the sidecar agrees.
    """
    try:
        recorded: object = json.loads(read_text_file(generated_dir / SOURCES_SIDECAR, layout))
    except (OSError, CodegenSetupError, json.JSONDecodeError):
        return [f"stale-source: {SOURCES_SIDECAR} — missing or unreadable, so staleness cannot be ruled out"]
    document: dict[str, Any] = cast("dict[str, Any]", recorded) if isinstance(recorded, dict) else {}
    sources: object = document.get("sources")
    derived: object = document.get("derived")
    if not isinstance(sources, dict):
        return [f'stale-source: {SOURCES_SIDECAR} — no "sources" map in the sidecar']
    if not isinstance(derived, dict):
        return [f'derived: {SOURCES_SIDECAR} — no "derived" map in the sidecar']
    recorded_sources = cast("dict[str, object]", sources)
    recorded_derived = cast("dict[str, object]", derived)
    problems: list[str] = []
    for source, digest in current_sources.items():
        if source not in recorded_sources:
            problems.append(f"stale-source: {source} — a new source the generated tree does not cover")
        elif recorded_sources[source] != digest:
            problems.append(f"stale-source: {source} — edited since the tree was generated")
    problems.extend(
        f"stale-source: {source} — recorded as a source but no longer on disk" for source in recorded_sources if source not in current_sources
    )
    for name in DERIVED_ARTIFACTS:
        try:
            actual: str | None = hash_source(read_text_file(generated_dir / name, layout))
        except (OSError, CodegenSetupError):
            actual = None
        if name not in recorded_derived:
            problems.append(f"derived: {name} — not recorded in {SOURCES_SIDECAR}")
        elif actual is None:
            problems.append(f"derived: {name} — recorded in {SOURCES_SIDECAR} but missing from the tree")
        elif actual != recorded_derived[name]:
            problems.append(f"derived: {name} — hand-edited since it was generated")
    problems.extend(
        f"derived: {name} — recorded in {SOURCES_SIDECAR} but no longer generated" for name in recorded_derived if name not in DERIVED_ARTIFACTS
    )
    return sorted(problems)


def is_contained_path(out_dir: Path, relative_path: str) -> bool:
    """Whether a path the server names stays strictly inside `out_dir` once resolved."""
    if os.path.isabs(relative_path) or relative_path.startswith(("/", "\\")):
        return False
    root = out_dir.resolve()
    return (root / relative_path).resolve().is_relative_to(root) and (root / relative_path).resolve() != root


def normalized_artifact_path(path: str) -> str:
    """A server-named path as a POSIX path with its dots folded, for the comparison with the writer's own files."""
    return os.path.normpath(path.replace("\\", "/")).replace("\\", "/")


def insecure_base_url_reason(base_url: str) -> str | None:
    """Why the key must not be sent to this base URL, or `None` when it may be.

    The gestures send the key as a bearer token and write what the server returns into the package,
    so anything beyond this machine must be reached over `https:`.
    """
    parsed = urlparse(base_url)
    if parsed.scheme == "https":
        return None
    if parsed.scheme != "http":
        return f"PIPELEX_BASE_URL must be an http(s) URL: {base_url}"
    host = (parsed.hostname or "").lower()
    if host in LOCAL_HOSTS or host.endswith(".localhost"):
        return None
    return (
        f"PIPELEX_BASE_URL uses plaintext http: for a non-local host ({base_url}). The codegen sends the API key as a "
        "bearer token and writes what the server returns into the package, so anything beyond localhost, 127.0.0.1 "
        "or [::1] must be https:."
    )
